### PR TITLE
MySQL unix fix

### LINKED ISSUE #2: Missing configuration/* files
Hello there. After building and trying to run the repox-gui-2.6.0-SNAPSHOT.war in Tomcat, I'm getting the following errors:
```
FATAL - Unable to load DefaultRepoxManager
java.io.FileNotFoundException: /vhosts/repoxdata/configuration/countries.txt (Permission denied)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
        at pt.utl.ist.configuration.DefaultRepoxContextUtil.getRepoxManager(DefaultRepoxContextUtil.java:52)
...//snip//...

Load Config files from Java Variables -- No Pre-Configured Log4j File found for REPOX
java.io.FileNotFoundException: /vhosts/repoxdata/configuration/metadataSchemas.xml (Permission denied)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
        at pt.utl.ist.util.XmlUtil.writePrettyPrint(XmlUtil.java:37)
...//snip//...
```
I was able to fix the first error by copying the `countries.txt` from `manager/target/classes/` up to our test server, but I'm not seeing a `metadataSchemas.xml`. Is this a file that should be included or generated in the repository, or should we be rolling our own?

Thanks for your time and trouble.
Cheers.

### PR DESCRIPTION
**Pull request by Guzmazow**
On unix systems with uppercase record-set record count won't generate because toLowerCase() wasn't used when checking table existance.
A bit additional code refactor to see where toLowerCase() happens.

### CODE REVIEW

**Comment by stzanakis** [comment]
Please do now commit after a pull request, if not communicated before.
I was about to merge the pull request and suddenly it was compiling, then realized there was another commit after that.
Also please remove the last commit with the ssl fddb118. There is another pull request that enables that.

**Comment by Guzmazow** [comment]
Sorry, i am not using github usually.

**Comment by Guzmazow** [comment]
Had to install desktop client to revert :)

**Comment by stzanakis** [comment]
No worries!:)
Thank you for the fix!

**Pull request merged**
